import React, { useState, useMemo } from "react";
import { useSoc } from "../context/SocContext.js";
import {
  ShieldAlert,
  Search,
  Filter,
  ArrowRight,
  ShieldCheck,
  CheckCircle2,
  XCircle,
  Clock,
  Layers,
  Zap,
  Terminal,
} from "lucide-react";
import { SeverityBadge } from "../components/common/SeverityBadge.js";
import { RiskScoreMeter } from "../components/common/RiskScoreMeter.js";
import { MitreTag } from "../components/common/MitreTag.js";
import { AlertStatus, Severity, DetectionSource } from "../types/soc.js";

export const AlertsView: React.FC = () => {
  const { alerts, openInvestigationForAlert, updateAlertStatus } = useSoc();

  const [search, setSearch] = useState("");
  const [selectedSeverity, setSelectedSeverity] = useState<string>("ALL");
  const [selectedStatus, setSelectedStatus] = useState<string>("ALL");
  const [selectedSource, setSelectedSource] = useState<string>("ALL");
  const [selectedAlerts, setSelectedAlerts] = useState<string[]>([]);

  // Filter logic
  const filtered = useMemo(() => {
    return alerts.filter((a) => {
      if (selectedSeverity !== "ALL" && a.severity !== selectedSeverity) return false;
      if (selectedStatus !== "ALL" && a.status !== selectedStatus) return false;
      if (selectedSource !== "ALL" && a.detectionSource !== selectedSource) return false;
      if (search.trim()) {
        const q = search.toLowerCase();
        return (
          a.title.toLowerCase().includes(q) ||
          a.host.toLowerCase().includes(q) ||
          a.sourceIp.toLowerCase().includes(q) ||
          a.username.toLowerCase().includes(q) ||
          a.id.toLowerCase().includes(q)
        );
      }
      return true;
    });
  }, [alerts, selectedSeverity, selectedStatus, selectedSource, search]);

  const handleSelectAll = (checked: boolean) => {
    if (checked) {
      setSelectedAlerts(filtered.map((a) => a.id));
    } else {
      setSelectedAlerts([]);
    }
  };

  const handleToggleSelect = (id: string) => {
    setSelectedAlerts((prev) =>
      prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]
    );
  };

  const handleBulkStatus = (status: AlertStatus) => {
    selectedAlerts.forEach((id) => updateAlertStatus(id, status));
    setSelectedAlerts([]);
  };

  return (
    <div className="p-6 space-y-6 max-w-[1600px] mx-auto overflow-y-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="px-2 py-0.5 rounded bg-red-950 border border-red-700/60 text-red-300 font-mono text-[11px] font-bold">
              INCIDENT TRIAGE QUEUE
            </span>
            <span className="text-xs text-slate-400 font-mono">
              Total Ingested Alerts: {alerts.length}
            </span>
          </div>
          <h1 className="text-2xl font-extrabold text-white tracking-tight mt-1">
            Security Alerts & Detections Management
          </h1>
          <p className="text-xs text-slate-400">
            Triaged security detections generated by Rule Engines, ML anomaly modeling, and Gemini reasoning.
          </p>
        </div>

        {/* Bulk Action Bar */}
        {selectedAlerts.length > 0 && (
          <div className="flex items-center gap-2 bg-slate-900 border border-slate-700 p-2 rounded-lg text-xs font-mono">
            <span className="text-cyan-400 font-bold px-2">{selectedAlerts.length} Selected:</span>
            <button
              onClick={() => handleBulkStatus("INVESTIGATING")}
              className="px-2.5 py-1 bg-cyan-950 hover:bg-cyan-900 border border-cyan-700 text-cyan-300 rounded font-semibold transition-colors"
            >
              Mark Investigating
            </button>
            <button
              onClick={() => handleBulkStatus("RESOLVED")}
              className="px-2.5 py-1 bg-emerald-950 hover:bg-emerald-900 border border-emerald-700 text-emerald-300 rounded font-semibold transition-colors"
            >
              Mark Resolved
            </button>
            <button
              onClick={() => handleBulkStatus("FALSE_POSITIVE")}
              className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded font-semibold transition-colors"
            >
              Mark FP
            </button>
          </div>
        )}
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-4 flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-3 flex-1">
          {/* Search */}
          <div className="relative w-full sm:w-72">
            <Search className="w-4 h-4 absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-500" />
            <input
              type="text"
              placeholder="Search by ID, title, IP, user..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-9 pr-3 py-1.5 bg-slate-950 border border-slate-700 rounded-lg text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-cyan-500 font-mono"
            />
          </div>

          {/* Severity */}
          <select
            value={selectedSeverity}
            onChange={(e) => setSelectedSeverity(e.target.value)}
            className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-cyan-500 font-mono"
          >
            <option value="ALL">All Severities</option>
            <option value="CRITICAL">Critical</option>
            <option value="HIGH">High</option>
            <option value="MEDIUM">Medium</option>
            <option value="LOW">Low</option>
          </select>

          {/* Status */}
          <select
            value={selectedStatus}
            onChange={(e) => setSelectedStatus(e.target.value)}
            className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-cyan-500 font-mono"
          >
            <option value="ALL">All Statuses</option>
            <option value="NEW">New</option>
            <option value="INVESTIGATING">Investigating</option>
            <option value="CONTAINED">Contained</option>
            <option value="RESOLVED">Resolved</option>
            <option value="FALSE_POSITIVE">False Positive</option>
          </select>

          {/* Source */}
          <select
            value={selectedSource}
            onChange={(e) => setSelectedSource(e.target.value)}
            className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-cyan-500 font-mono"
          >
            <option value="ALL">All Sources</option>
            <option value="RULE_BASED">Rule-Based</option>
            <option value="ML_ANOMALY">ML Anomaly</option>
            <option value="GEMINI_AI">Gemini AI</option>
          </select>
        </div>

        <span className="text-xs text-slate-400 font-mono">
          Showing <strong className="text-white">{filtered.length}</strong> alerts
        </span>
      </div>

      {/* Main Table */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-xl overflow-hidden shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-950 text-slate-400 uppercase font-mono text-[11px] border-b border-slate-800">
              <tr>
                <th className="px-4 py-3 w-8">
                  <input
                    type="checkbox"
                    checked={selectedAlerts.length > 0 && selectedAlerts.length === filtered.length}
                    onChange={(e) => handleSelectAll(e.target.checked)}
                    className="rounded bg-slate-800 border-slate-700 text-cyan-500 focus:ring-0"
                  />
                </th>
                <th className="px-4 py-3">Alert ID / Timestamp</th>
                <th className="px-4 py-3">Detection Summary & Techniques</th>
                <th className="px-4 py-3">Severity</th>
                <th className="px-4 py-3">Risk Meter</th>
                <th className="px-4 py-3">Target Host</th>
                <th className="px-4 py-3">Threat Source IP</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-slate-300">
              {filtered.length === 0 ? (
                <tr>
                  <td colSpan={9} className="text-center py-12 text-slate-500 font-mono">
                    No alerts match the active filter criteria.
                  </td>
                </tr>
              ) : (
                filtered.map((alert) => {
                  const isChecked = selectedAlerts.includes(alert.id);
                  return (
                    <tr
                      key={alert.id}
                      className={`hover:bg-slate-800/40 transition-colors cursor-pointer ${
                        isChecked ? "bg-cyan-950/20" : ""
                      }`}
                      onClick={() => openInvestigationForAlert(alert.id)}
                    >
                      <td className="px-4 py-3" onClick={(e) => e.stopPropagation()}>
                        <input
                          type="checkbox"
                          checked={isChecked}
                          onChange={() => handleToggleSelect(alert.id)}
                          className="rounded bg-slate-800 border-slate-700 text-cyan-500 focus:ring-0"
                        />
                      </td>

                      {/* ID & Time */}
                      <td className="px-4 py-3 font-mono">
                        <div className="font-bold text-cyan-400">{alert.id}</div>
                        <div className="text-[10px] text-slate-400">
                          {alert.timestamp.replace("T", " ").replace("Z", "")}
                        </div>
                      </td>

                      {/* Title & MITRE Tags */}
                      <td className="px-4 py-3">
                        <div className="font-semibold text-slate-100">{alert.title}</div>
                        <p className="text-[11px] text-slate-400 line-clamp-1 mt-0.5">
                          {alert.description}
                        </p>
                        <div className="flex flex-wrap items-center gap-1.5 mt-1.5">
                          <span className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-slate-800 text-slate-400 border border-slate-700">
                            {alert.detectionSource}
                          </span>
                          {alert.mitreTechniques.map((t) => (
                            <MitreTag key={t.id} technique={t} compact />
                          ))}
                        </div>
                      </td>

                      {/* Severity */}
                      <td className="px-4 py-3">
                        <SeverityBadge severity={alert.severity} size="sm" />
                      </td>

                      {/* Risk Meter */}
                      <td className="px-4 py-3">
                        <RiskScoreMeter score={alert.riskScore} compact />
                      </td>

                      {/* Host */}
                      <td className="px-4 py-3 font-mono text-[11px]">
                        <span className="font-bold text-slate-200">{alert.host}</span>
                        <div className="text-[10px] text-slate-400">user: {alert.username}</div>
                      </td>

                      {/* Source IP */}
                      <td className="px-4 py-3 font-mono text-[11px] text-cyan-300">
                        {alert.sourceIp}
                      </td>

                      {/* Status */}
                      <td className="px-4 py-3" onClick={(e) => e.stopPropagation()}>
                        <select
                          value={alert.status}
                          onChange={(e) => updateAlertStatus(alert.id, e.target.value as AlertStatus)}
                          className="bg-slate-950 border border-slate-700 rounded px-2 py-1 text-[11px] font-mono text-slate-300 focus:outline-none focus:border-cyan-500"
                        >
                          <option value="NEW">NEW</option>
                          <option value="INVESTIGATING">INVESTIGATING</option>
                          <option value="CONTAINED">CONTAINED</option>
                          <option value="RESOLVED">RESOLVED</option>
                          <option value="FALSE_POSITIVE">FALSE POSITIVE</option>
                        </select>
                      </td>

                      {/* Actions */}
                      <td className="px-4 py-3 text-right" onClick={(e) => e.stopPropagation()}>
                        <button
                          onClick={() => openInvestigationForAlert(alert.id)}
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-950/80 hover:bg-indigo-900 border border-indigo-500/50 text-indigo-200 text-xs font-semibold shadow-sm transition-all"
                        >
                          <span>Investigate</span>
                          <ArrowRight className="w-3.5 h-3.5 text-cyan-400" />
                        </button>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
